### ISSUE TITLE
quimage not available ?

### ISSUE THREAD

**Issue by gedw99** [hugelgupf/vmtest#122]
this is a really useful code for working with u-root and plan9.

I am wondering if quimage, which is mentioned in the README, is available yet ?

I think it will  help me with cross testing

**Comment by gedw99** [comment]
found it :)

will close..

**Comment by hugelgupf** [comment]
My apologies, I fixed the link in the README :)

**Comment by gedw99** [comment]
Yeah that was what put me off .

great project btw .
